name: Test and Lint Python Package

on:
  push:
    branches:
      - '**'        # matches every branch
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-dev
    - name: Run checks (linter, code style, tests)
      run: make check
      working-directory: .
      env:
        DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        DATABRICKS_CLUSTER_ID: ${{ vars.DATABRICKS_CLUSTER_ID }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
